### PR TITLE
Wc plugin CSS modifications

### PR DESCRIPTION
**Pull request by jdsmith022**

### CODE REVIEW

**Comment by jdsmith022** [comment]
small adjustments to css to correct plugin for myomy.nl: 

effects of changes on myomy.nl inspect:

Screenshot 2020-09-14 at 13 23 54


effects of changes tested in Docker:
Screenshot 2020-09-14 at 13 24 06

Screenshot 2020-09-14 at 13 32 59

**Comment by Mil0dV** [comment]
Looks good! 2 things:
- you forgot to update the docker image (although it is a slight abuse of this PR)
- the changes to css are more extensive than I expected (or hoped) so let's test this tomorrow on our testserver (I'll show you around)

**Comment by jdsmith022** [comment]
test changes made to .css file on themes on testing server

result achieved on myomy.nl:

Screen Shot 2020-09-15 at 5 23 01 PM
Screen Shot 2020-09-15 at 5 24 47 PM

this result was achieved on all themes tested on test server bar two.

**Found two edges cases:**

Enfold theme:
changes have set margin-top: 9px !important;
for enfold it should be margin-top: 12px;
current layout with margin-top: 9px

Screen Shot 2020-09-15 at 5 25 02 PM

co2ok theme:
display: inline-block causes co2ok_payoff_text to align too far right. Removing display: inline-block achieve's desired effect, but further testing would need to be done with other themes to resolve. 
also, entire alignment of content within button is set lower, again this would need to be tested further in comparison with other themes to find solution:

Screen Shot 2020-09-15 at 5 25 16 PM

**Comment by Mil0dV** [comment]
LGTM

:shipit:

**Review by Mil0dV — APPROVED** [review]
LGTM

:shipit:

**Pull request merged**
